### ISSUE TITLE
CentOSでデータベースのmigrationに失敗する

### ISSUE THREAD

**Issue by ishigakim** [lodge/lodge#116]
CentOS6.4でインストール中に以下のエラーが出てしまいます。Fedoraでテストしたときには出ないエラーです。Rubyの知識がないので，ご対応頂ければ幸いです。
Rubyは1.9.3-p547，Gemは2.4.1です。データベースはMySQLです。

```
$ bundle exec rake db:migrate RAILS_ENV=production
rake aborted!
NoMethodError: undefined method `to_sym' for nil:NilClass
/home/ishigaki/Soft/lodge/config/environments/production.rb:94:in `block in <top (required)>'
/home/ishigaki/Soft/lodge/vendor/bundle/ruby/1.9.1/gems/railties-4.1.6/lib/rails/railtie.rb:210:in `instance_eval'
/home/ishigaki/Soft/lodge/vendor/bundle/ruby/1.9.1/gems/railties-4.1.6/lib/rails/railtie.rb:210:in `configure'
/home/ishigaki/Soft/lodge/config/environments/production.rb:2:in `<top (required)>'
/home/ishigaki/Soft/lodge/vendor/bundle/ruby/1.9.1/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:247:in `require'
/home/ishigaki/Soft/lodge/vendor/bundle/ruby/1.9.1/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:247:in `block in require'
/home/ishigaki/Soft/lodge/vendor/bundle/ruby/1.9.1/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:232:in `load_dependency'
/home/ishigaki/Soft/lodge/vendor/bundle/ruby/1.9.1/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:247:in `require'
/home/ishigaki/Soft/lodge/vendor/bundle/ruby/1.9.1/gems/railties-4.1.6/lib/rails/engine.rb:594:in `block (2 levels) in <class:Engine>'
/home/ishigaki/Soft/lodge/vendor/bundle/ruby/1.9.1/gems/railties-4.1.6/lib/rails/engine.rb:593:in `each'
/home/ishigaki/Soft/lodge/vendor/bundle/ruby/1.9.1/gems/railties-4.1.6/lib/rails/engine.rb:593:in `block in <class:Engine>'
/home/ishigaki/Soft/lodge/vendor/bundle/ruby/1.9.1/gems/railties-4.1.6/lib/rails/initializable.rb:30:in `instance_exec'
/home/ishigaki/Soft/lodge/vendor/bundle/ruby/1.9.1/gems/railties-4.1.6/lib/rails/initializable.rb:30:in `run'
/home/ishigaki/Soft/lodge/vendor/bundle/ruby/1.9.1/gems/railties-4.1.6/lib/rails/initializable.rb:55:in `block in run_initializers'
/home/ishigaki/Soft/lodge/vendor/bundle/ruby/1.9.1/gems/railties-4.1.6/lib/rails/initializable.rb:44:in `each'
/home/ishigaki/Soft/lodge/vendor/bundle/ruby/1.9.1/gems/railties-4.1.6/lib/rails/initializable.rb:44:in `tsort_each_child'
/home/ishigaki/Soft/lodge/vendor/bundle/ruby/1.9.1/gems/railties-4.1.6/lib/rails/initializable.rb:54:in `run_initializers'
/home/ishigaki/Soft/lodge/vendor/bundle/ruby/1.9.1/gems/railties-4.1.6/lib/rails/application.rb:300:in `initialize!'
/home/ishigaki/Soft/lodge/config/environment.rb:5:in `<top (required)>'
/home/ishigaki/Soft/lodge/vendor/bundle/ruby/1.9.1/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:247:in `require'
/home/ishigaki/Soft/lodge/vendor/bundle/ruby/1.9.1/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:247:in `block in require'
/home/ishigaki/Soft/lodge/vendor/bundle/ruby/1.9.1/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:232:in `load_dependency'
/home/ishigaki/Soft/lodge/vendor/bundle/ruby/1.9.1/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:247:in `require'
/home/ishigaki/Soft/lodge/vendor/bundle/ruby/1.9.1/gems/railties-4.1.6/lib/rails/application.rb:276:in `require_environment!'
/home/ishigaki/Soft/lodge/vendor/bundle/ruby/1.9.1/gems/railties-4.1.6/lib/rails/application.rb:389:in `block in run_tasks_blocks'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
```

**Comment by kakusuke** [comment]
rubyのバージョンが1.9.1に見えます

**Comment by ishigakim** [comment]
```
$ ruby -v
ruby 1.9.3p547 (2014-05-14 revision 45962) [x86_64-linux]
```

コマンドで確認してみても1.9.3となっています。ruby自体はrbenvでインストールし，yumでインストールしたrubyは消したので，1.9.1が入りそうな理由が思いつきません。

**Comment by kakusuke** [comment]
そうですか…
ちなみに.envは用意しておりすでしょうか？

**Comment by ishigakim** [comment]
.envを設定して，やり直してみましたが，同様のエラーが出ます。

rubyのバージョンが1.9.1となる問題がきになったので，見なおしたら，.rbenvディレクトリ以下に~/.rbenv/versions/1.9.3-p547/include/ruby-1.9.1/というディレクトリができていました。/usr以下に1.9.1があったような覚えがありますが，その設定がどこか来ているのかよくわかりません。ここで何か競合しているのでしょうか。

**Comment by ishigakim** [comment]
rubyを2.0.0にしてもダメでした。。。

```
rake aborted!
NoMethodError: undefined method `to_sym' for nil:NilClass
/home/ishigaki/Soft/lodge/config/environments/production.rb:101:in `block in <top (required)>'
/home/ishigaki/Soft/lodge/vendor/bundle/ruby/2.0.0/gems/railties-4.1.6/lib/rails/railtie.rb:210:in `instance_eval'
/home/ishigaki/Soft/lodge/vendor/bundle/ruby/2.0.0/gems/railties-4.1.6/lib/rails/railtie.rb:210:in `configure'
/home/ishigaki/Soft/lodge/config/environments/production.rb:2:in `<top (required)>'
/home/ishigaki/Soft/lodge/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:247:in `require'
/home/ishigaki/Soft/lodge/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:247:in `block in require'
/home/ishigaki/Soft/lodge/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:232:in `load_dependency'
/home/ishigaki/Soft/lodge/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:247:in `require'
/home/ishigaki/Soft/lodge/vendor/bundle/ruby/2.0.0/gems/railties-4.1.6/lib/rails/engine.rb:594:in `block (2 levels) in <class:Engine>'
/home/ishigaki/Soft/lodge/vendor/bundle/ruby/2.0.0/gems/railties-4.1.6/lib/rails/engine.rb:593:in `each'
/home/ishigaki/Soft/lodge/vendor/bundle/ruby/2.0.0/gems/railties-4.1.6/lib/rails/engine.rb:593:in `block in <class:Engine>'
/home/ishigaki/Soft/lodge/vendor/bundle/ruby/2.0.0/gems/railties-4.1.6/lib/rails/initializable.rb:30:in `instance_exec'
/home/ishigaki/Soft/lodge/vendor/bundle/ruby/2.0.0/gems/railties-4.1.6/lib/rails/initializable.rb:30:in `run'
/home/ishigaki/Soft/lodge/vendor/bundle/ruby/2.0.0/gems/railties-4.1.6/lib/rails/initializable.rb:55:in `block in run_initializers'
/home/ishigaki/Soft/lodge/vendor/bundle/ruby/2.0.0/gems/railties-4.1.6/lib/rails/initializable.rb:44:in `each'
/home/ishigaki/Soft/lodge/vendor/bundle/ruby/2.0.0/gems/railties-4.1.6/lib/rails/initializable.rb:44:in `tsort_each_child'
/home/ishigaki/Soft/lodge/vendor/bundle/ruby/2.0.0/gems/railties-4.1.6/lib/rails/initializable.rb:54:in `run_initializers'
/home/ishigaki/Soft/lodge/vendor/bundle/ruby/2.0.0/gems/railties-4.1.6/lib/rails/application.rb:300:in `initialize!'
/home/ishigaki/Soft/lodge/config/environment.rb:5:in `<top (required)>'
/home/ishigaki/Soft/lodge/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:247:in `require'
/home/ishigaki/Soft/lodge/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:247:in `block in require'
/home/ishigaki/Soft/lodge/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:232:in `load_dependency'
/home/ishigaki/Soft/lodge/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:247:in `require'
/home/ishigaki/Soft/lodge/vendor/bundle/ruby/2.0.0/gems/railties-4.1.6/lib/rails/application.rb:276:in `require_environment!'
/home/ishigaki/Soft/lodge/vendor/bundle/ruby/2.0.0/gems/railties-4.1.6/lib/rails/application.rb:389:in `block in run_tasks_blocks'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
```

**Comment by a-know** [comment]
@ishigakim さん
初めまして。私もつい先日、[ほぼ同じような環境（CentOS6.5）にて試した](http://blog.a-know.me/entry/2014/09/14/124323) のですが、
最初は同様のエラーが出たように記憶しています。

やったこととしては、migration の前に .env を用意（適切な値をセットする）してから、migration を実施する、という、 @ishigakim さんがすでに試されているのと同じようなことなのですが、
私は disposable な環境であったこともあり、インスタンスを削除してやり直したので、その点では差異があるかもしれません。
- .env を用意する前に `db:migrate`
- 失敗する
- .env を用意する
- `db:rollback` する
- `db:migrate` する

...なども、すでに試されましたでしょうか？

**Comment by kakusuke** [comment]
`.env`に`SMTP_AUTH_METHOD`は記述してありますでしょうか？
それが記述されていない場合、上記のようなエラーメッセージが出るようです

**Comment by ishigakim** [comment]
a-knowさん，kakusukeさんありがとうございました。おかげさまでrake:migrateはできるようになりました。原因は.envにSMTP_AUTH_METHODをコメントアウトしていたためでした。

はれて，データベースもできたし，lodgeを起動したのはいいのですが，今度は新規登録でつまづいています。会社のメールの送信サーバーが認証なしのため，SMTP_AUTH_METHODをコメントアウトして使う必要があります。GmailなどのWebメールも制限がかかっていて，使えないしという状況です。送信サーバの認証なしの場合はどう設定すればいいんでしょうか。

**Comment by ishigakim** [comment]
なんとかなりました。
config/enviroments/production.rbのsmtpの設定を下記のように修正したところ，無事認証メールが届くようになりました。どうもお騒がせしました。

``` diff
diff --git a/config/environments/production.rb b/config/environments/production.rb
index 7aa2d7b..bb78a7c 100644
--- a/config/environments/production.rb
+++ b/config/environments/production.rb
@@ -96,9 +96,9 @@ Rails.application.configure do
     :address              => ENV["SMTP_ADDRESS"],
     :port                 => ENV["SMTP_PORT"],
     :domain               => ENV["LODGE_DOMAIN"],
-    :user_name            => ENV["SMTP_USERNAME"],
-    :password             => ENV["SMTP_PASSWORD"],
-    :authentication       => ENV["SMTP_AUTH_METHOD"].to_sym,
-    :enable_starttls_auto => ENV["SMTP_ENABLE_STARTTLS_AUTO"],
+#    :user_name            => ENV["SMTP_USERNAME"],
+#    :password             => ENV["SMTP_PASSWORD"],
+#    :authentication       => ENV["SMTP_AUTH_METHOD"].to_sym,
+#    :enable_starttls_auto => ENV["SMTP_ENABLE_STARTTLS_AUTO"],
   }
 end
```

**Comment by m-yamashita** [comment]
@ishigakim さん、マニュアル外の対応をさせてしまい申し訳ありません。
対策を考えて対応したいと思いますので、一先ずはその設定で凌いでいただけますでしょうか？

そして @kakusuke さんご対応ありがとうございました。忙しくてなかなか手を付けられなくて申し訳ございません。。。
恒久的な対策ができるまで、Issueはこのまま残しておくことにします。

**Comment by ishigakim** [comment]
今回の件はとりあえず，.envの設定を先にするようにすれば回避できるような気がします。インストールガイドは.envの設定が後に書いてあるので，順番を変更するのはどうでしょうか。

送信メールサーバの認証がないほうがまれだと思いますので，production.rbの変更はかなりイレギュラーだと思います。

**Comment by shiena** [comment]
横から失礼します。
私が設置した環境ではメールサーバがTLSかつSSL証明書が自己証明書だったため、以下のパラメータが必要でした。こちらも考慮いただければ助かります。

``` diff
diff --git a/config/environments/production.rb b/config/environments/production.rb
index 7aa2d7b..b5f3150 100644
--- a/config/environments/production.rb
+++ b/config/environments/production.rb
@@ -100,5 +100,7 @@ Rails.application.configure do
     :password             => ENV["SMTP_PASSWORD"],
     :authentication       => ENV["SMTP_AUTH_METHOD"].to_sym,
     :enable_starttls_auto => ENV["SMTP_ENABLE_STARTTLS_AUTO"],
+    :tls                  => true,
+    :openssl_verify_mode  => 'none'
   }
 end
```
