### ISSUE TITLE
フォローできないタグがある

### ISSUE THREAD

**Issue by shiena** [lodge/lodge#118]
タグ名に日本語を含んでいたり`.`を含んでいると、そのタグをフォローできません。
以下は`自動化`タグと`D3.js`タグをフォローしたときのログです。

```
$ tail -0f log/production.log 
I, [2014-09-17T17:50:51.460315 #13301]  INFO -- : Started POST "/tags/%E8%87%AA%E5%8B%95%E5%8C%96/follow" for 10.0.2.2 at 2014-09-17 17:50:51 +0000
F, [2014-09-17T17:50:51.463454 #13301] FATAL -- : 
ActionController::BadRequest (ActionController::BadRequest):
  config/initializers/quiet_assets.rb:6:in `call_with_quiet_assets'


I, [2014-09-17T17:50:54.722279 #13301]  INFO -- : Started POST "/tags/D3.js/follow" for 10.0.2.2 at 2014-09-17 17:50:54 +0000
F, [2014-09-17T17:50:54.724018 #13301] FATAL -- : 
ActionController::RoutingError (No route matches [POST] "/tags/D3.js/follow"):
  config/initializers/quiet_assets.rb:6:in `call_with_quiet_assets'
```

**Comment by shiena** [comment]
すみません、別の環境で確認したら日本語タグのフォローできました。
フォローできる環境はMySQL、できない環境はSQLIte3の違いがあります。
今、できない環境を確認できないので他にも違いがあるかもしれません。

**Comment by m-yamashita** [comment]
ご報告ありがとうございました。調査したいと思います。

**Comment by shiena** [comment]
bundle updateすると日本語のタグをフォローできるようになりました。
`.`を含むタグは相変わらずフォローできません。
以下はアップデートされたgem一覧です。

```
Installing activesupport 4.1.6 (was 4.1.5)
Installing actionview 4.1.6 (was 4.1.5)
Installing actionpack 4.1.6 (was 4.1.5)
Installing mime-types 2.3 (was 1.25.1)
Installing mail 2.6.1 (was 2.5.4)
Installing actionmailer 4.1.6 (was 4.1.5)
Installing activemodel 4.1.6 (was 4.1.5)
Installing activerecord 4.1.6 (was 4.1.5)
Installing railties 4.1.6 (was 4.1.5)
Installing bootswatch-rails 3.2.4 (was 3.2.3)
Installing tins 1.3.3 (was 1.3.2)
Installing rails 4.1.6 (was 4.1.5)
Installing rdoc 4.1.2 (was 4.1.1)
Installing rspec-core 3.1.4 (was 3.1.1)
Installing rspec-expectations 3.1.1 (was 3.1.0)
Installing rspec-mocks 3.1.1 (was 3.1.0)
```

**Comment by m-yamashita** [comment]
#122, #136  により修正しました。
次回リリース後IssueをCloseします。

**Comment by m-yamashita** [comment]
v0.10.3 によりリリースしました。よってCloseします。

**Comment by shiena** [comment]
修正ありがとうございます。
`.`を含むタグをフォローできるようになりました。
