### ISSUE TITLE
gemoji 3でtask/emoji.rakeが無くなっている

### ISSUE THREAD

**Issue by sho-suzuki** [lodge/lodge#181]
こんにちは。
本日ruby2.1, 2.3で起動しようとした所、下記のエラーが出ました。

```bash
# bundle exec rake
rake aborted!
LoadError: cannot load such file -- tasks/emoji.rake
/lodge/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.0/lib/active_support/dependencies.rb:241:in `load'
/lodge/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.0/lib/active_support/dependencies.rb:241:in `block in load'
/lodge/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.0/lib/active_support/dependencies.rb:232:in `load_dependency'
/lodge/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.0/lib/active_support/dependencies.rb:241:in `load'
/lodge/Rakefile:5:in `<top (required)>'
/lodge/vendor/bundle/ruby/2.1.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)
```

gem versionを見てみると gemoji 3.0.0となっており、emoji.rakeが見当たりませんでした。
Gemfileに　`gem 'gemoji' '~> 2.0'`
と入れてbundle exec rakeしたら動くようになりました。

gemojiのversionを指定するか、もしくはRakefile内のload文を削除戴けませんでしょうか？

**Comment by naofumi-fujii** [comment]
👍

**Comment by m-yamashita** [comment]
https://github.com/lodge/lodge/pull/183 にて対応済みです。
リリース後Closeします。
