### ISSUE TITLE
公式のテスト実行方法を記載してほしい

### ISSUE THREAD

**Issue by comuttun** [lodge/lodge#36]
すみません、単純に Ruby 素人なせいなのですが、 `rspec` を使ったテスト実行方法がわかりません。

``` bash
$ bundle exec rspec test/
No examples found.


Finished in 0.00025 seconds (files took 1.42 seconds to load)
```

``` bash
$ bundle exec rspec --pattern test/*/*_test.rb
/vagrant/test/controllers/comment_controller_test.rb:1:in `require': cannot load such file -- test_helper (LoadError)
    from /vagrant/test/controllers/comment_controller_test.rb:1:in `<top (required)>'
    from /vagrant/vendor/bundler/ruby/2.1.0/gems/rspec-core-3.0.2/lib/rspec/core/configuration.rb:1057:in `load'
    from /vagrant/vendor/bundler/ruby/2.1.0/gems/rspec-core-3.0.2/lib/rspec/core/configuration.rb:1057:in `block in load_spec_files'
    from /vagrant/vendor/bundler/ruby/2.1.0/gems/rspec-core-3.0.2/lib/rspec/core/configuration.rb:1057:in `each'
    from /vagrant/vendor/bundler/ruby/2.1.0/gems/rspec-core-3.0.2/lib/rspec/core/configuration.rb:1057:in `load_spec_files'
    from /vagrant/vendor/bundler/ruby/2.1.0/gems/rspec-core-3.0.2/lib/rspec/core/runner.rb:97:in `setup'
    from /vagrant/vendor/bundler/ruby/2.1.0/gems/rspec-core-3.0.2/lib/rspec/core/runner.rb:85:in `run'
    from /vagrant/vendor/bundler/ruby/2.1.0/gems/rspec-core-3.0.2/lib/rspec/core/runner.rb:70:in `run'
    from /vagrant/vendor/bundler/ruby/2.1.0/gems/rspec-core-3.0.2/lib/rspec/core/runner.rb:38:in `invoke'
    from /vagrant/vendor/bundler/ruby/2.1.0/gems/rspec-core-3.0.2/exe/rspec:4:in `<top (required)>'
    from /vagrant/vendor/bundler/ruby/2.1.0/bin/rspec:23:in `load'
    from /vagrant/vendor/bundler/ruby/2.1.0/bin/rspec:23:in `<main>'
```

**Comment by kakusuke** [comment]
実は rspec のテストは test 以下でななく、spec 以下なのです・・・
特にディレクトリを指定する必要はなく、`bundle exec rspec`とするだけでいいと思います

**Comment by comuttun** [comment]
@kakusuke 以下のようにだめでした。

``` bash
$ bundle exec rspec
/vagrant/vendor/bundler/ruby/2.1.0/gems/rspec-core-3.0.2/lib/rspec/core/configuration.rb:1057:in `load': cannot load such file -- /vagrant/spec (LoadError)
    from /vagrant/vendor/bundler/ruby/2.1.0/gems/rspec-core-3.0.2/lib/rspec/core/configuration.rb:1057:in `block in load_spec_files'
    from /vagrant/vendor/bundler/ruby/2.1.0/gems/rspec-core-3.0.2/lib/rspec/core/configuration.rb:1057:in `each'
    from /vagrant/vendor/bundler/ruby/2.1.0/gems/rspec-core-3.0.2/lib/rspec/core/configuration.rb:1057:in `load_spec_files'
    from /vagrant/vendor/bundler/ruby/2.1.0/gems/rspec-core-3.0.2/lib/rspec/core/runner.rb:97:in `setup'
    from /vagrant/vendor/bundler/ruby/2.1.0/gems/rspec-core-3.0.2/lib/rspec/core/runner.rb:85:in `run'
    from /vagrant/vendor/bundler/ruby/2.1.0/gems/rspec-core-3.0.2/lib/rspec/core/runner.rb:70:in `run'
    from /vagrant/vendor/bundler/ruby/2.1.0/gems/rspec-core-3.0.2/lib/rspec/core/runner.rb:38:in `invoke'
    from /vagrant/vendor/bundler/ruby/2.1.0/gems/rspec-core-3.0.2/exe/rspec:4:in `<top (required)>'
    from /vagrant/vendor/bundler/ruby/2.1.0/bin/rspec:23:in `load'
    from /vagrant/vendor/bundler/ruby/2.1.0/bin/rspec:23:in `<main>'
```

spec ディレクトリがそもそも存在しないのですが、何か勘違いしていますでしょうか？

``` bash
$ find . -name spec
./vendor/bundler/ruby/2.1.0/bundler/gems/yaml_db-fb4b6bd7e12d/spec
./vendor/bundler/ruby/2.1.0/gems/acts-as-taggable-on-3.2.6/spec
./vendor/bundler/ruby/2.1.0/gems/after_commit_action-0.1.3/spec
./vendor/bundler/ruby/2.1.0/gems/awesome_print-1.2.0/spec
./vendor/bundler/ruby/2.1.0/gems/bcrypt-3.1.7/spec
./vendor/bundler/ruby/2.1.0/gems/bullet-4.11.3/spec
./vendor/bundler/ruby/2.1.0/gems/celluloid-0.15.2/spec
./vendor/bundler/ruby/2.1.0/gems/counter_culture-0.1.24/spec
./vendor/bundler/ruby/2.1.0/gems/diff-lcs-1.2.5/spec
./vendor/bundler/ruby/2.1.0/gems/diffy-3.0.5/spec
./vendor/bundler/ruby/2.1.0/gems/dotenv-0.11.1/spec
./vendor/bundler/ruby/2.1.0/gems/ffi-1.9.3/spec
./vendor/bundler/ruby/2.1.0/gems/guard-rspec-4.2.10/spec
./vendor/bundler/ruby/2.1.0/gems/kaminari-0.16.1/spec
./vendor/bundler/ruby/2.1.0/gems/listen-2.7.9/spec
./vendor/bundler/ruby/2.1.0/gems/lumberjack-1.0.9/spec
./vendor/bundler/ruby/2.1.0/gems/multi_json-1.10.1/spec
./vendor/bundler/ruby/2.1.0/gems/mysql2-0.3.16/spec
./vendor/bundler/ruby/2.1.0/gems/orm_adapter-0.5.0/spec
./vendor/bundler/ruby/2.1.0/gems/rack-test-0.6.2/spec
./vendor/bundler/ruby/2.1.0/gems/rb-fsevent-0.9.4/spec
./vendor/bundler/ruby/2.1.0/gems/rspec-core-3.0.2/lib/rspec/core/project_initializer/spec
./vendor/bundler/ruby/2.1.0/gems/rspec-rails-3.0.1/lib/generators/rspec/install/templates/spec
./vendor/bundler/ruby/2.1.0/gems/rspec-support-3.0.2/lib/rspec/support/spec
./vendor/bundler/ruby/2.1.0/gems/sass-3.2.19/vendor/listen/spec
./vendor/bundler/ruby/2.1.0/gems/sdoc-0.4.0/spec
./vendor/bundler/ruby/2.1.0/gems/thor-0.19.1/spec
./vendor/bundler/ruby/2.1.0/gems/timers-1.1.0/spec
./vendor/bundler/ruby/2.1.0/gems/treetop-1.4.15/spec
./vendor/bundler/ruby/2.1.0/gems/uglifier-2.5.1/spec
./vendor/bundler/ruby/2.1.0/gems/uniform_notifier-1.6.2/spec
./vendor/bundler/ruby/2.1.0/gems/warden-1.2.3/spec
```

**Comment by kakusuke** [comment]
rspec は #30 で導入したので、まだ develop ブランチにしかありませんが、
今いるブランチは master だったりしませんか？

**Comment by comuttun** [comment]
失礼しました、古い develop を見ておりました (__;
実行することができました。
標準的な方法ですので、あえて記述する必要もないかと思いますので、クローズしちゃいます。
